### ISSUE TITLE
No comfortable way to bind multiple keys to one handler function

### ISSUE THREAD

**Issue by mrbar42** [matthewoden/keyevents-npm#1]
Currently `componentKeyEvents()` is called on every 'keydown' (twice actually).
While I don't understand what's the idea of having the target component returning an object of keys in general,
it prevents assigning multiple keys to one handler directly.

of-coarse it can be hacked like this:

``` javascript
    componentKeyEvents:function(){
        var submitHandler = function () {console.log("submitted!")};
        return{
            enter:submitHandler,
            space: submitHandler
        }
    }
```

But its a bad practice in my vission.

I would suggest this change

``` javascript
    // mixin code
    onKeyDown: function(event) {
        var keyPressed = KEYS[event.which];
        this.componentKeyEvent(keyPressed);
    }

    // target component code
    componentKeyEvent: function(key){
        switch(key) {
            case 'enter':
            case 'space':
                console.log("submitted!");
                break;
            case 'escape':
                this._myComponentMethod();
                break
        }
    }
```

Either way... its really unnecessary to call componentKeyEvents twice

**Comment by matthewoden** [comment]
While I don't agree with changing the lookup to a switch (which seems to have been made popular thanks to flux), I understand the need to feel comfortable with your code. The key lookup should really be an implementation detail. This library shouldn't force your hand, or change your coding style.

So, similar to what you suggested:

``` javascript
 // mixin code
    onKeyDown: function(event) {
        var keyPressed = KEYS[event.which];
        this.componentKeyEvent(keyPressed);
        // maybe something that captures multiple key presses.
    }

    // target component code
    componentKeyEvent: function(key){
        // whatever you want to do to find that key.
       // run a switch, return an object key, etc.

    }
```

I'll also look into that double keydown call. Thanks for the feedback!

**Comment by matthewoden** [comment]
@mrbar42 I've updated the library, but can't seem to reproduce the double-call of componentKeyEvents. Can you provide sample code?

**Comment by mrbar42** [comment]
You removed the double calling - its fixed.

**Comment by matthewoden** [comment]
@mrbar42 Rad! Thanks again!
